---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  tasks:
    - name: Run template
      template:
          src: "files/SG.yml.j2"
          dest: "SG.template"