---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml
  tasks:
    - name: Run template
      template:
          src: "files/ssm_doc.yml.j2"
          dest: "./ssm_doc.template"