---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: 'formate test'
      shell: cat /tmp/test.json
      register: result

    - name: 'print test'
      shell: echo "{{ result.stdout | to_yaml }} >> /tmp/test.yaml"
