---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    doc_contents: "{{ lookup('file', './ssm_doc/ssm_doc_content.yml') }}"
  tasks:
    - name: Run template
      template:
          src: "files/ssm_doc.yml.j2"
          dest: "./ssm_doc.template"
