---
- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
  - name: 'formate test'
  - shell: cat /tmp/test.json
    register: result

  - set_fact:
      myvar: "{{ result.stdout | from_json }}"
