---
- hosts: localhost
  tasks:
  - name: run the new module
    ssm_dev:
      document_name: 'EC2Test'
      region: 'ap-southeast-2'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
